/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n7.1.1-56-gc2184b65d2-20250804"
#endif /* AVUTIL_FFVERSION_H */
